# arduino-test-compile-ActionTest.yml
# Github workflow script for testing the arduino-test-compile action development.
#
# Copyright (C) 2020  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
# License: MIT
#

# This is the name of the workflow, visible on GitHub UI.
name: Arduino Compile
on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - 'arduino-test-compile.sh'
    - '*.yml'
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples

    runs-on: ubuntu-latest # ubuntu-latest # I picked Ubuntu to use shell scripts.

    env:
      # Comma separated list without double quotes around the list.
     CLI_VERSION: latest

    strategy:
      matrix:
        # The matrix will produce one job for each configuration parameter of type `arduino-boards-fqbn`
        # In the Arduino IDE, the fqbn is printed in the first line of the verbose output for compilation as parameter -fqbn=... for the "arduino-builder -dump-prefs" command
        #
        # Examples: arduino:avr:uno, arduino:avr:leonardo, arduino:avr:nano, arduino:avr:mega
        # arduino:sam:arduino_due_x, arduino:samd:arduino_zero_native"
        # ATTinyCore:avr:attinyx5:chip=85,clock=1internal, digistump:avr:digispark-tiny, digistump:avr:digispark-pro
        # STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C8
        # esp8266:esp8266:huzzah:eesz=4M3M,xtal=80, esp32:esp32:featheresp32:FlashFreq=80
        # You may add a suffix behind the fqbn with "|" to specify one board for e.g. different compile options like arduino:avr:uno|trace
        #############################################################################################################
        arduino-boards-fqbn:
          - m5stack:esp32:core

        # Specify parameters for each board.
        #############################################################################################################
        include:
          - arduino-boards-fqbn: m5stack:esp32:core
            platform-url: https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json
            sketches-exclude: WhistleSwitch,50Hz,SimpleFrequencyDetector

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout custom library
        uses: actions/checkout@v3
        with:
          repository: ArminJo/ATtinySerialOut
          ref: master
          path: CustomLibrary # must match the pattern *Custom*

      # Test of the arduino-test-compile action
      - name: Compile all examples using the arduino-test-compile action
        # uses: ArminJo/arduino-test-compile@master
        uses: ./.github/actions
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          arduino-platform: ${{ matrix.arduino-platform }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          sketches-exclude: ${{ matrix.sketches-exclude }}
          build-properties: ${{ toJson(matrix.build-properties) }}
          sketch-names: "*.ino"
          sketch-names-find-start: "examples/*"
          debug-compile: true
          debug-install: true
